id: P006635
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:11:50.235924
source_metadata:
  id: bdr:W5743
  title: ལྷ་ཆོས་དང་མཐུན་པའི་གཏམ
  author: ''
  volumes:
    5dc0ffdd36c34f54a13b705b5909650a:
      image_group_id: I5043
      title: ''
      volume_number: 1
      total_pages: 82
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
